In [2]:
import numpy as np

1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [4]:
np.version.version

'1.26.4'

2. Write a NumPy program to get help on the add function.

In [193]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

3. Write a NumPy program to test whether none of the elements of a given array is zero.


In [9]:
x = np.array([1,2,3,4])
np.all(x)

True

4. Write a NumPy program to test whether any of the elements of a given array is non-zero.


In [45]:
kunnu = np.array([0,0,0,0])
kunnu1 = np.array([1,2,3,4])
print(np.any(kunnu))
print(np.any(kunnu1))

False
True


5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).


In [11]:
x = np.array([1, 0, np.nan, np.inf])
np.isfinite(x)

array([ True,  True, False, False])

6. Write a NumPy program to test element-wise for positive or negative infinity.


In [12]:
x = np.array([1, 0, np.nan, np.inf])
np.isinf(x)

array([False, False, False,  True])

7. Write a NumPy program to test element-wise for NaN of a given array.

In [194]:
x = np.array([1, 0, np.nan, np.inf])
np.isnan(x)

array([False, False,  True, False])

8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.


In [14]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.iscomplex(x)

array([ True, False, False, False, False,  True])

9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.


In [22]:
a = [1,6,3,4,5]
b = [6,4,3,9,0]
# Greater Number
print("Greater  Number is:         ",np.greater(a,b))
# Greater Equal
print("Greater Equal  Number is:   ",np.greater_equal(a,b))
# Less Number
print("Less  Number is:            ",np.less(a,b))
# Less Equal
print("Less Equal  Number is:      ",np.less_equal(a,b))

Greater  Number is:          [False  True False False  True]
Greater Equal  Number is:    [False  True  True False  True]
Less  Number is:             [ True False False  True False]
Less Equal  Number is:       [ True False  True  True False]


10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.


In [23]:
x = np.array([1, 7, 13, 105])
print("Size of the memory occupied by the array: ",x.size * x.itemsize)

Size of the memory occupied by the array:  32


11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [24]:
print("An array of 10 zeros: ",np.zeros(10))
print("An array of 10 ones: ",np.ones(10))
print("An array of 10 fives: ",np.ones(10)*5)

An array of 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


12. Write a NumPy program to create an array of the integers from 30 to70.


In [25]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

13. Write a NumPy program to create an array of all the even integers from 30 to 70.


In [26]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

14. Write a NumPy program to create a 3x3 identity matrix.


In [34]:
np.identity(3)        # We cannot change Diagonal within the matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(3,k=1)        # We can change Diagonal within the matrix

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

15. Write a NumPy program to generate a random number between 0 and 1.


In [35]:
np.random.normal(0,1,1)

array([-0.34964435])

16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.


In [36]:
np.random.normal(0,1,15)

array([ 0.18547918, -0.26927258,  0.06081302, -1.1589618 ,  1.4054203 ,
        0.29588715,  0.71761542,  1.62865343, -1.732849  , -0.25816401,
       -0.18585756, -0.42332507,  1.18077435, -3.03582827, -0.7022354 ])

17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.


In [39]:
np.arange(16,55)

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

18. Write a NumPy program to create a 3X4 array.


In [43]:
print(np.arange(10,22).reshape(3,4))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


19. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.


In [42]:
print(np.linspace(5,50,10))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.


In [44]:
x = np.arange(0,21)
x[(x>=9) & (x<=15)] *= -1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.


In [47]:
np.random.randint(0,11,5)

array([8, 3, 6, 8, 4])

22. Write a NumPy program to multiply the values of two given vectors.


In [49]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
vector_mul = a*b
print(vector_mul)

[ 5 12 21 32]


23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.


In [52]:
print(np.arange(10,22).reshape(3,4))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


24. Write a NumPy program to find the number of rows and columns of a given matrix.


In [55]:
x = np.arange(10,22).reshape(3,4)
print(x)
print("Number of rows:    ",x.shape[0])
print("Number of columns: ",x.shape[1])

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows:     3
Number of columns:  4


25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.


In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.


In [61]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.


In [68]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.


In [70]:
np.arange(0,27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

29. Write a NumPy program to compute the inner product of two given vectors.


In [121]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
print(a)
print(b)

print("Inner Product is : \n",np.inner(a,b))
print("Dot Product is :  \n",np.dot(a,b))

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
Inner Product is : 
 [[11 17]
 [25 39]]
Dot Product is :  
 [[13 16]
 [29 36]]


30. Write a NumPy program to sort a given array by row and column in ascending order.


In [122]:
a = np.array([9,6,7,3])
print(np.sort(a))

[3 6 7 9]


31. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.


In [170]:
a = np.array([11,22,33,55,66,77,88,99])
print(a[a>55])
print(a[a<55])
# Anoter way
print(a[a != 55])
# Anoter way
arr = a[(a>55) | (a<55)]
print(arr)

[66 77 88 99]
[11 22 33]
[11 22 33 66 77 88 99]
[11 22 33 66 77 88 99]


32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.


In [175]:
a = np.array([11,22,33,55,66,77,88,99])
a[(a>55)] = 0
print("Greater Number: ",a)
a = np.array([11,22,33,55,66,77,88,99])
a[(a<55)] = 0
print("Less Number:    ",a)
a = np.array([11,22,33,55,66,77,88,99])
a[(a==55)] = 0
print("Equal Number:   ",a)

Greater Number:  [11 22 33 55  0  0  0  0]
Less Number:     [ 0  0  0 55 66 77 88 99]
Equal Number:    [11 22 33  0 66 77 88 99]


33. Write a NumPy program to create an array of equal shape and data type of a given array.


In [188]:
a = np.array([11,22,33,55,66,77,88,99])
print(a)
print(np.empty_like(a))

[11 22 33 55 66 77 88 99]
[99249998409066              0              0              0
              0              0              0              0]


34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.


In [189]:
a = np.arange(0,60).reshape(3,5,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]]



35. Write a NumPy program to multiply two given arrays of same size element-by-element.


In [192]:
a = np.array([11,22,33,55,66,77,88,99])
b = np.array([99,88,77,66,55,33,22,11])
print(a*b)

[1089 1936 2541 3630 3630 2541 1936 1089]


**THANK YOU!**



