In [5]:
import pandas as pd
import numpy as np

In [6]:
i = [x for x in range(1,21)]
i

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [7]:
list1 =[i for i in range(1,6)]
list2 =[i for i in range(6,11)]
list3 =[i for i in range(11,16)]
list4 =[i for i in range(16,21)]

In [8]:
array1 = np.array([list1,list2])
array2 = np.array([list3,list4])
array1, array2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [14]:
arraysum= array1+array2
arraysum

[array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]])]

In [15]:
arraymul = array1*array2
arraymul

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [16]:
arraysub = array1-array2
arraysub 

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [17]:
arrayexpo = np.exp(array1)
arrayexpo

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])