In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)
mydata = np.random.randint(0,100,(4,3))
print(mydata)      # just a numpy array

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [3]:
myindex = ['CA', 'NY', 'AZ', 'TX']
mycolumns = ['Jan','Feb','Mar']

df = pd.DataFrame(data=mydata)
print(df)    # only numeric index

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63


In [4]:
df = pd.DataFrame(data=mydata, index=myindex)
print(df)         # label index

     0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63


In [5]:
df = pd.DataFrame(data=mydata, index=myindex, columns=mycolumns)
print(df)       # label index with columns    

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63


In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes
None
