In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [4]:
print(type(my_list))

<class 'list'>


In [5]:
# Create numpy array from list
print(np.array(my_list))

[1 2 3]


In [6]:
# Or from a list of a list
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(np.arange(0,11,2))

[ 0  2  4  6  8 10]


In [9]:
print(np.zeros(3))

[0. 0. 0.]


In [11]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
print(np.ones(3))

[1. 1. 1.]


In [14]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
print(np.linspace(0,10,3))

[ 0.  5. 10.]


In [17]:
print(np.linspace(0,5,20))

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [18]:
print(np.linspace(0,5,21))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [23]:
# Random Number arrays
print(np.random.rand(2))
print(np.random.rand(5,5))

[0.15498185 0.66377464]
[[0.8373086  0.19675849 0.15497049 0.19560795 0.0445291 ]
 [0.43995834 0.60521514 0.30507471 0.04632194 0.90903389]
 [0.51995739 0.53341957 0.97878221 0.60074675 0.70538581]
 [0.29911861 0.52634059 0.61902051 0.26416215 0.48928526]
 [0.20525523 0.07971661 0.69169902 0.86693905 0.33617694]]


In [24]:
# From normal distribution 
print(np.random.randn(2)) # Function used to generate random value close to zero(can be +ve and -ve value) 
print(np.random.randn(5,5))

[-1.8381015   0.74108851]
[[ 0.47023147 -0.48556336 -1.04135837  0.20213858 -1.58357837]
 [ 0.78841887 -1.81037055 -1.31522833 -0.61514415 -0.06204753]
 [-1.26581986 -0.11515888 -1.39810226 -1.18254883  2.33584124]
 [ 1.89661628 -0.14527896  0.229963   -0.64465494 -2.19658549]
 [ 1.20238526  1.98753682  0.27234652  0.18287579  2.21780633]]


In [75]:
# Random sampling function in numpy, Return the array of specified shape and fills it random float
print(np.random.ranf(4))

[0.4964146  0.67356546 0.93930446 0.35401226]


In [25]:
# Random integers form low (inclusive) to high (exlusive)
print(np.random.randint(1,100))                      # Single random integer between  1 - 100
print(np.random.randint(1,100,10))                   # 10 random integer between  1 - 100

53
[37 35 51 22 13 26  7 10 12 67]


In [27]:
# Seed the unpredictability (means all of us should get same random number)
# To check or compair the result

In [28]:
# Seeding for reproducable results
np.random.seed(77)
print(np.random.rand(4))           # 4 random numbers

[0.91910903 0.6421956  0.75371223 0.13931457]


In [29]:
# Sorting

In [43]:
arr = np.arange(25)      # Numbers from 0-25
print(arr)
ranarr = np.random.randint(0,50,10)        # 10 random numbers between 0 - 50
print("\n",ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 [44 37 26 17 34 25  4 44 35  9]


In [44]:
# Reshape: Returns an array conntaining the same data with a new shape
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [45]:
# Max, Min and their index positions

In [46]:
print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())


44
0
4


#  Creating Sample Array

In [48]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [49]:
# Bracket indexing and selection - similar to python list
# Get a value at an index  
print(arr[8])

8


In [50]:
# Get value in a range
print(arr[1:5])

[1 2 3 4]


In [51]:
# Get value in a range
print(arr[0:5])

[0 1 2 3 4]


In [52]:
# Brodcasting
# Setting a valu with index range (Broadcasting)
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [53]:
# Reset array 
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
# Important note on Slice
slice_of_arr = arr[0:6]
print(slice_of_arr)

[1 2 3 4 5 6]


In [56]:
# Change Slice
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[99 99 99 99 99 99]
[99 99 99 99 99 99  7  8  9 10]


In [58]:
# Toget actual copy, we need .copy method()

In [59]:
# Conditional Section 
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
# Change made are also in our original array!
# Data is not copy, it is a another view of original array!
# and False otherwise
print(arr>4)

[False False False False  True  True  True  True  True  True]


In [61]:
# Store boolen result in another array
bool_arr = arr>4
print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [70]:
# Select only those elements form the arr array where the corresponding elements from in bool_arr is True
# It effectively filters out the elements of arr where the condition arr > 4 is True
print(arr[bool_arr])

[4 5 6 7 8 9]


In [ ]:
# Operatios in NumPy

In [62]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
# Basic Arethmatic
print(arr + arr)
print(arr * arr)
print(arr - arr)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]


In [64]:
# This will raise a warning on division by zeros, but not an error! 
# It just  fill the spot with nan
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\DAI.STUDENTSDC\AppData\Local\Temp\ipykernel_4808\135280326.py:3: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


In [65]:
# Also  waring (but not an error)  relating to infinity
print(1/arr)
print(arr**3)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[  0   1   8  27  64 125 216 343 512 729]


C:\Users\DAI.STUDENTSDC\AppData\Local\Temp\ipykernel_4808\2341962743.py:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [66]:
# Universal function
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\DAI.STUDENTSDC\AppData\Local\Temp\ipykernel_4808\2742828541.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [67]:
# Summary Statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [68]:
# 2D array

In [69]:
# This is a 2- Dimentional array with 3 rows and 4 coloumns
arr_2d = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
# Row and Column count
print(arr_2d.shape)

(3, 4)


In [73]:
# Sum all the rows for each row 
print(arr_2d.sum(axis=0))

[15 18 21 24]


In [74]:
# Sum all the columns for each column
print(arr_2d.sum(axis=1))

[10 26 42]
